licenses(["notice"])

package(default_visibility = ["//visibility:public"])

# List of packages that can use Arcs.
# Public visibility for now.
package_group(
    name = "allowed-packages",
    packages = [
        "//...",
    ],
)
