steps:
# Pull most recent Docker image.
- id: 'pull-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:head']
  waitFor: ['-']

# Build the new Docker image (caching from the pre-built one)
- id: 'build-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--cache-from=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:head',
         '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}/branches/$BRANCH_NAME:head',
         '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}/branches/$BRANCH_NAME:$COMMIT_SHA',
         '--tag=test-image'
         '.']

- id: 'sigh-build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['run',
         '--rm',
         'test-image',
         'tools/sigh build']
  waitFor: ['build-image']

substitutions:
  _IMAGE_NAME: arcs
