steps:
# Pull most recent Docker image.
- id: 'pull-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:head']
  waitFor: ['-']

# Build the new Docker image (caching from the pre-built one)
- id: 'build-image'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:head',
    '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:head',
    '--tag=arcs-base',
    '.',
  ]
  waitFor: ['pull-image']

# Push updated Docker image to Container Registry.
- id: 'push-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:head']
  waitFor: ['build-image']

- id: 'local-presubmit'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'run',
    '--network=cloudbuild',
    '--rm', 'arcs-base',
    'tools/local-presubmit',
    '--bazelrc=tools/gcb.bazelrc',
  ]
  waitFor: ['build-image']

images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'

timeout: 3600s # 60 mins, just in case.
logsBucket: 'gs://arcs-github-gcb-logs'
options:
  machineType: 'N1_HIGHCPU_32'

substitutions:
  _IMAGE_NAME: arcs
