// tslint:disable
// Temporarily generated by the wasm build process (but needs to be checked into src)
export const WasmConfig = {
  MEMORY_BASE: 1024,
  DYNAMIC_BASE: 5250688,
  DYNAMICTOP_PTR: 7552
};
