
licenses(["notice"])

java_test(
    name = "AllTests",
    srcs = glob(["*.java"]),
    size = "small",
    test_class = "arcs.android.impl.AllTests",
    deps = [
        "//javaharness/java/arcs/android:impl",
        "@junit//jar",
        "//javaharness/java/arcs/api:api-android",
    ],
)

