/*
 * Copyright 2020 Google LLC.
 *
 * This code may only be used under the BSD style license found at
 * http://polymer.github.io/LICENSE.txt
 *
 * Code distributed by Google as part of this project is also subject to an additional IP rights
 * grant found at
 * http://polymer.github.io/PATENTS.txt
 */

package arcs.sdk

import arcs.core.storage.api.Entity
import arcs.core.storage.api.EntitySpec

/** Base class of all generated [Entity] types. */
typealias Entity = arcs.core.storage.api.Entity

/**
 * Spec for an [Entity] type. Can create and deserialize new entities.
 *
 * Implementation classes are autogenerated for each entity type.
 */
typealias EntitySpec<T> = arcs.core.storage.api.EntitySpec<T>
