# Wrapper script around Emscripten command line tools (i.e. em++).
sh_binary(
    name = "emsdk_wrapper",
    srcs = ["emsdk_wrapper.sh"],
    data = ["@emsdk//:all_files"],
    visibility = ["//visibility:public"],
)
