
licenses(["notice"])

java_test(
    name = "AllTests",
    srcs = glob(["*.java"]),
    size = "small",
    test_class = "arcs.android.impl.AllTests",
    deps = [
        "//java/arcs/android/impl:impl",
        "@junit//jar",
        "//java/arcs/api",
    ],
)

