load(
    "//third_party/java/arcs/build_defs:build_defs.bzl",
    "arcs_manifest",
)

package(default_visibility = ["//visibility:public"])

arcs_manifest(
    name = "quality_store",
    srcs = ["quality.arcs"],
    deps = ["quality.json"],
)
