{{- if .Values.certManager.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
      - name: clouddns
        clouddns:
          project: {{ .Values.project }}
          serviceAccountSecretRef:
            name: prod-clouddns-svc-acct-secret
            key: prod-clouddns-service-account.json
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
      namespace: cert-manager
    dns01:
      providers:
      - name: clouddns
        clouddns:
          project: {{ .Values.project }}
          serviceAccountSecretRef:
            name: prod-clouddns-svc-acct-secret
            key: prod-clouddns-service-account.json
{{- end }}
