apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "arcs.fullname" . }}
  labels:
    app: {{ include "arcs.name" . }}
    chart: {{ include "arcs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "arcs.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "arcs.name" . }}
        arcs: master
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ARCS_MASTER
            value: "true"
          - name: MY_APP_NAME
            value: "{{ include "arcs.name" . }}"
          - name: MY_RELEASE_NAME
            value: "{{ .Release.Name }}"
          - name: MY_NODE_NAME
            value: "{{ include "arcs.fullname" . }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
