workspace(name = "arcs_enclave")



# Note that the Asylo version is also specified in Dockerfile.
http_archive(
    name = "com_google_asylo",
    urls = ["https://github.com/google/asylo/archive/v0.2.1.tar.gz"],
    strip_prefix = "asylo-0.2.1",
    sha256 = "ba8589b9178846292235997270e13a558843974af0aca1ee908f62651e4f59a7",
)

# TODO remove? with source files?
#load("//asdf:include-protobuf.bzl", "include_protobuf")
#include_protobuf()

load("@com_google_asylo//asylo/bazel:asylo_deps.bzl", "asylo_deps",
     "asylo_testonly_deps")
asylo_deps()
asylo_testonly_deps()

load("@com_google_asylo//asylo/bazel:sgx_deps.bzl", "sgx_deps")
sgx_deps()

