licenses(["notice"])

java_test(
    name = "AllTests",
    size = "small",
    srcs = glob(["*.java"]),
    test_class = "arcs.api.AllTests",
    deps = [
        "//third_party/java/junit",
        "//javaharness/java/arcs/api:api-android",
    ],
)
