
licenses(["notice"])

java_test(
    name = "AllTests",
    srcs = glob(["*.java"]),
    size = "small",
    test_class = "arcs.api.AllTests",
    deps = [
        "@junit//jar",
        "//javaharness/java/arcs/api:api-android",
    ],
)

