load("//build_defs:build_defs.bzl", "arcs_kt_particle")

arcs_kt_particle(
    name = "ParentParticle",
    srcs = ["ParentParticle.kt"],
)

arcs_kt_particle(
    name = "ChildParticle",
    srcs = ["ChildParticle.kt"],
)
