load("//third_party/java/arcs/build_defs:build_defs.bzl", "arcs_kt_binary")

arcs_kt_binary(
    name = "ParentParticle",
    srcs = ["ParentParticle.kt"],
)

arcs_kt_binary(
    name = "ChildParticle",
    srcs = ["ChildParticle.kt"],
)
