load("//build_defs/emscripten:build_defs.bzl", "cc_wasm_library")

cc_wasm_library(
    name = "arcs",
    srcs = [
        "arcs.cc",
        # "example.cc",
    ],
    hdrs = [
        "arcs.h",
        # "example.h",
    ],
    visibility = ["//visibility:public"],
)
