load("//third_party/bazel_rules/rules_kotlin/kotlin/native:native_rules.bzl", "kt_native_library")
load("//third_party/java/arcs/build_defs:build_defs.bzl", "arcs_kt_jvm_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "arcs",
    srcs = glob(["*.kt"]),
)

