#!/usr/bin/env node

// Copyright (c) 2017 Google Inc. All rights reserved.
// This code may only be used under the BSD style license found at
// http://polymer.github.io/LICENSE.txt
// Code distributed by Google as part of this project is also
// subject to an additional IP rights grant found at
// http://polymer.github.io/PATENTS.txt

'use strict';

const path = require('path');
const { spawnSync } = require('child_process');

var result = 0;

// Rather than spawning a new wdio for every version, it might be possible to
// have a single wdio/wdio.conf.js that includes references to all paths.
// However, the current arrangement makes the baseUrl much simpler, and the
// inefficiencies seem bearable.
process.argv.slice(2).forEach(wdioConfig => {
  const version = wdioConfig.split(path.sep)[0];
  console.log('running web tests on version', version);

  const ret = spawnSync(
    'wdio',
    [
      '-b',
      `http://${process.env.npm_package_config_host}:${process.env.npm_package_config_port}/`,
      `test/wdio.conf.js`
    ],
    { cwd: path.resolve(version), stdio: 'inherit' }
  );
  if (ret.status>0) {
    console.log(`ERROR: failure (status code ${ret.status}) due to errors in ${version}`);
    result = ret.status;
  }
});

process.exit(result);
