/*
 * Copyright 2020 Google LLC.
 *
 * This code may only be used under the BSD style license found at
 * http://polymer.github.io/LICENSE.txt
 *
 * Code distributed by Google as part of this project is also subject to an additional IP rights
 * grant found at
 * http://polymer.github.io/PATENTS.txt
 */

package arcs.android.util

import android.os.Debug
import arcs.core.util.performance.MemoryIdentifier
import arcs.core.util.performance.MemoryStats

/** Extends Debug.MemoryInfo to query [name]'s memory usage as a Long value. */
fun Debug.MemoryInfo.getMemoryStatLong(name: String): Long =
    this.getMemoryStat(name)?.toLongOrNull() ?: 0L

/** Connects Android-specific memory-stats implementation to [MemoryStats] */
fun connectMemoryStatsPipe() {
    MemoryStats.pipe = {
        with(Debug.MemoryInfo().apply { Debug.getMemoryInfo(this) }) {
            // Keys are from frameworks/base/core/java/android/os/Debug.java
            // The memory usage is generated by walking through the /self/smaps of current
            // process and retrieving stats from libmemtrack for graphics.
            mapOf(
                MemoryIdentifier.TOTAL to getMemoryStatLong("summary.total-pss"),
                MemoryIdentifier.JAVA_HEAP to getMemoryStatLong("summary.java-heap"),
                MemoryIdentifier.NATIVE_HEAP to getMemoryStatLong("summary.native-heap"),
                MemoryIdentifier.CODE_STATIC to getMemoryStatLong("summary.code"),
                MemoryIdentifier.STACK to getMemoryStatLong("summary.stack"),
                MemoryIdentifier.GRAPHICS to getMemoryStatLong("summary.graphics"),
                MemoryIdentifier.SYSTEM to getMemoryStatLong("summary.system"),
                MemoryIdentifier.OTHER to getMemoryStatLong("summary.private-other")
            )
        }
    }
}
