load("//third_party/bazel_rules/rules_kotlin/kotlin/native:native_rules.bzl", "kt_native_library")

licenses(["notice"])

kt_native_library(
    name = "wasm",
    srcs = glob(["*.kt"]),
    visibility = ["//visibility:public"],
)
