#!/bin/bash
#
# A basic script to build android apks for testing.
set -e

source $(dirname $0)/logging.sh
# Temporary hack to pass bazelrc file for running the bazel tests in google cloud build.
# We could get rid of this if we split up these commands as steps in cloudbuild.
# See https://github.com/PolymerLabs/arcs/issues/4550
BAZELRC_OPTS=$1

cd $ROOT
status "Building Android apks."

set -x

# Build apks used by Firebase Test Labs and copy them to /workspace which
# can be used be next Cloud Build step.
./tools/bazelisk ${BAZELRC_OPTS} build //javatests/arcs/android/e2e/testapp //javatests/arcs/android/e2e
cp ./bazel-bin/javatests/arcs/android/e2e/testapp/testapp.apk /workspace
cp ./bazel-bin/javatests/arcs/android/e2e/e2e.apk /workspace
