#!/bin/bash
# Script to check all files copy right statements are up to date.

source $(dirname $0)/logging.sh

OIFS="$IFS"
IFS=$'\n'
for file in $(git ls-files)
do
  notice=$(grep "Copyright [0-9].*\(Google\|Polymer\)" "${file}" | sed "s/^[^0-9-]*//" | sed "s/[^0-9-]*$//")
  if [ ! -z "$notice" ]
  then
    edited=$(git log -1 "${file}" | head -n1 | cut -d' ' -f6)
    if [ ! "$notice" = "$edited" ]
    then
      warn "${file} $notice year: $edited"
      sed -i "s/$notice/$edited/g" "$file"
    fi
  fi
done
IFS="$OIFS"
