#!/bin/bash
#
# Installs the Android SDK. Supply a single command line arg: the location for
# where to install the SDK (defaults to $HOME/Android/Sdk).
set -e

source $(dirname $0)/logging.sh

TARGET=${1:-"$HOME/Android/Sdk"}

mkdir -p "$TARGET"

curl -s https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > "$TARGET/sdk.zip"
unzip -q "$TARGET/sdk.zip" -d "$TARGET"
rm "$TARGET/sdk.zip"

mkdir -p "$TARGET/licenses"
echo "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $TARGET/licenses/android-sdk-license

mkdir -p "$HOME/.android"
touch "$HOME/.android/repositories.cfg"
${TARGET}/tools/bin/sdkmanager --update

yes | $TARGET/tools/bin/sdkmanager --licenses

while read -r package; do
  PACKAGES="${PACKAGES}${package} "
done < "$(dirname $0)/android-sdk-packages.txt"

"$TARGET/tools/bin/sdkmanager" ${PACKAGES}

if [[ -z $ANDROID_HOME ]]; then
  warn "Don't forget to set the ANDROID_HOME environment variable!
Add the following line to your .bashrc file:

export ANDROID_HOME=\"$TARGET\"
"
fi
