#!/bin/sh

ROOT=$(dirname $0)/..
(cd $ROOT && npm install)
npm install -g bower
(cd $ROOT/devtools && npm install && bower install)
(cd $ROOT/strategy-explorer && bower install)
(cd $ROOT/extension && npm install)
