#!/bin/bash

source $(dirname $0)/logging.sh

cd $ROOT

# TODO(wkorman): Consider moving ktlint to a sigh or blaze task.
status "Running ktlint on any Kotlin files modified w.r.t. upstream/master..."
git diff --name-only --relative upstream/master | grep '\.kt[s\"]\?$' | xargs ktlint --android --relative --verbose .
