#!/bin/bash

source $(dirname $0)/logging.sh

cd $ROOT

# TODO(wkorman): Consider moving ktlint to a sigh or blaze task.
status "Running ktlint on any Kotlin files modified w.r.t. upstream/master..."
BASE=$(git merge-base HEAD upstream/master)
if [[ $BASE ]]; then
  git diff --name-only --relative $BASE | grep '\.kt[s\"]\?$' | xargs ktlint --android --relative --verbose
else
  fail "Could not determine the common ancestor for HEAD and upstream/master"
fi
