#!/bin/bash

source $(dirname $0)/logging.sh

gnuxargs=$(xargs --version 2>&1 |grep -s GNU >/dev/null && echo true || echo false)

function portable_xargs_r() {
  if $gnuxargs ; then
    cat - | xargs -r """$@"""
  else
    cat - | xargs """$@"""
  fi
}

cd $ROOT

# TODO(wkorman): Consider moving ktlint to a sigh or blaze task.
status "Running ktlint on any Kotlin files modified w.r.t. upstream/master..."
BASE=$(git merge-base HEAD upstream/master)
if [[ $BASE ]]; then
  git diff --name-only --relative $BASE | grep '\.kt[s\"]\?$' | portable_xargs_r ktlint --android --relative --verbose
else
  fail "Could not determine the common ancestor for HEAD and upstream/master"
fi
