#!/bin/bash
#
# A basic script to locally semi-simulate the build and test
# operations performed by our continuous integration service. Note
# that this does not do a clean and reinstall of npm modules and
# sigh/bazel artifacts.
set -e

source $(dirname $0)/logging.sh

cd $ROOT
status "Testing all of the things."

./tools/sigh webpack
./tools/bazelisk test //java/... //javatests/... //src/... //particles/...
./tools/sigh testShells
./tools/sigh lint
./tools/sigh test

