#!/bin/bash
#
# A basic script to locally semi-simulate the build and test
# operations performed by our continuous integration service. Note
# that this does not do a clean and reinstall of npm modules and
# sigh/bazel artifacts.
set -e

source $(dirname $0)/logging.sh
# Temporary hack to pass bazelrc file for running the bazel tests in google cloud build.
# We could get rid of this if we split up these commands as steps in cloudbuild.
# See https://github.com/PolymerLabs/arcs/issues/4550
BAZELRC_OPTS=$1

cd $ROOT
status "Testing all of the things."

set -x

./tools/sigh webpack
#./tools/bazelisk ${BAZELRC_OPTS} test //javatests/arcs/sdk/wasm:test-module //src/... //particles/...
./tools/bazelisk ${BAZELRC_OPTS} test //java/... //javatests/... //src/... //particles/...
./tools/sigh testShells
./tools/sigh lint
./tools/sigh test --all
