#!/bin/bash
#
# A basic script to run Android e2e tests on locally on a dev phone or emulator.
set -e

source $(dirname $0)/logging.sh

cd $ROOT
status "Testing Android e2e tests."

set -x


./tools/bazelisk build javatests/arcs/android/e2e/testapp && \
    ./tools/bazelisk build javatests/arcs/android/e2e && \
    adb install bazel-bin/javatests/arcs/android/e2e/testapp/testapp.apk && \
    adb install bazel-bin/javatests/arcs/android/e2e/e2e.apk && \
    adb shell am instrument -w arcs.android.e2e/androidx.test.runner.AndroidJUnitRunner
