#!/bin/sh
# Script to run CI steps within a docker image (specified by tools/Dockerfile.CI)
cd $(dirname $0)/..
docker run -v $(pwd):/usr/src/app/ arcsproject/travis-build:latest /bin/sh -c "cd /usr/src/app; $1"
