#!/bin/sh

ROOT=$(dirname $0)/..

echo "1. Install nvm"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | sh || \
  (echo 'Failed to download the latest version of nvm.'; exit 1)

echo "1.1 ensure nvm is in your current process"
source ~/.nvm/nvm.sh || \
  (echo 'Failed to ensure nvm is in this process.'; exit 1)

echo "2. Install node"
nvm install 10 || \
  (echo 'Failed to install node version 10.'; exit 1)

echo "3. Update npm to later version"
npm install -g npm  || \
  (echo 'Failed to update npm to latest version.'; exit 1) 

echo "4. Install node_modules"
(cd $ROOT && npm install) || \
  (echo 'Failed to install node_modules.'; exit 1)

echo "5. Build the project"
$ROOT/tools/sigh || \
  (echo 'Failed to build project with `sigh`.'; exit 1)

