filegroup(
    name = "core_srcs",
    srcs = glob([
        "gen/**",
        "planning/**/*.ts",
        "platform/**/*.ts",
        "runtime/**/*.ts",
        "services/**/*.ts",
    ]),
    visibility = ["//visibility:public"],
)
