# Wrapper script around Kotlin-Native command line tools (i.e. kotlinc).

sh_binary(
    name = "kotlinc_wrapper",
    srcs = ["kotlinc_wrapper.sh"],
    data = ["@kotlin_native_local//:all_artifacts"],
    visibility = ["//visibility:public"],
)
