#!/bin/bash
#
# Generates an Arcs root manifest from command line arguments. An import is
# added for all command line args passed in that end with .arcs (files not
# ending in .arcs are ignored). The root manifest is output to stdout.
#
# This script is designed to be used by the arcs_manifest_bundle BUILD rule.
#
# Usage: generate_root_manifest.sh \
#     path/to/generating:rule \
#     path/to/one.arcs \
#     path/to/two.arcs \
#     path/to/irrelevent.file

echo "// Root manifest generated by $1"

for file in "$@"; do
  if [[ $file == *.arcs ]]; then
    echo "import '$file';"
  fi
done
